# Generated by Django 6.0.5 on 2026-10-03 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('is_whatsapp', models.BooleanField(default=False, verbose_name='هل الرقم واتساب')),
                ('subscribe_whatsapp', models.BooleanField(default=False, verbose_name='اشتراك واتساب')),
                ('subscribe_email', models.BooleanField(default=False, verbose_name='اشتراك بريدي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
