# Generated by Django 6.0.5 on 2026-08-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='company_name',
            field=models.CharField(default=1, max_length=200, verbose_name='اسم الشركة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='full_name',
            field=models.CharField(default=1, max_length=200, verbose_name='الاسم الكامل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='is_whatsapp',
            field=models.BooleanField(default=False, verbose_name='هل الرقم واتساب'),
        ),
        migrations.AddField(
            model_name='trial',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='trial',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='subscribe_email',
            field=models.BooleanField(default=False, verbose_name='اشتراك بريدي'),
        ),
        migrations.AddField(
            model_name='trial',
            name='subscribe_whatsapp',
            field=models.BooleanField(default=False, verbose_name='اشتراك واتساب'),
        ),
    ]
