# Generated by Django 4.2.16 on 2026-10-03 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='أدخل أسم شركتك  ', max_length=255, verbose_name='اسم الشركة')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('contact_email', models.EmailField(default='info@example.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(default='+966 12 345 6789', max_length=20, verbose_name='رقم الهاتف')),
                ('contact_address', models.CharField(default='المملكة العربية السعودية', max_length=255, verbose_name='العنوان')),
                ('social_facebook', models.URLField(blank=True, null=True, verbose_name='فيسبوك')),
                ('social_twitter', models.URLField(blank=True, null=True, verbose_name='تويتر')),
                ('social_instagram', models.URLField(blank=True, null=True, verbose_name='انستغرام')),
                ('social_linkedin', models.URLField(blank=True, null=True, verbose_name='لينكد إن')),
                ('footer_quick_links_title', models.CharField(default='روابط سريعة', max_length=100, verbose_name='عنوان روابط سريعة')),
                ('footer_features_title', models.CharField(default='المميزات', max_length=100, verbose_name='عنوان المميزات')),
                ('footer_contact_title', models.CharField(default='تواصل معنا', max_length=100, verbose_name='عنوان التواصل')),
                ('footer_copyright_text', models.CharField(default='جميع الحقوق محفوظة', max_length=255, verbose_name='نص حقوق النشر')),
                ('quick_link_support', models.URLField(blank=True, null=True, verbose_name='رابط الدعم الفني')),
                ('quick_link_guide', models.URLField(blank=True, null=True, verbose_name='رابط دليل الاستخدام')),
                ('quick_link_faq', models.URLField(blank=True, null=True, verbose_name='رابط الأسئلة الشائعة')),
                ('feature_invoices', models.URLField(blank=True, null=True, verbose_name='رابط إدارة الفواتير')),
                ('feature_inventory', models.URLField(blank=True, null=True, verbose_name='رابط إدارة المخزون')),
                ('feature_reports', models.URLField(blank=True, null=True, verbose_name='رابط التقارير الذكية')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الواتساب (مع رمز الدولة، مثال: 966501234567)')),
                ('whatsapp_message', models.CharField(blank=True, default='مرحباً، أتواصل معكم من المتجر، كيف يمكنكم مساعدتي؟', max_length=255, null=True, verbose_name='رسالة واتساب التلقائية')),
                ('fb_page_id', models.CharField(blank=True, help_text='أدخل رقم المعرف الخاص بصفحتك على فيسبوك فقط.', max_length=100, null=True, verbose_name='معرف صفحة الفيسبوك (Page ID)')),
                ('fb_access_token', models.CharField(blank=True, help_text='أدخل الرمز الذي تحصل عليه من موقع مطوري فيسبوك (Developers Facebook). تنبيه: هذا الرمز سري، لا تشاركه مع أحد.', max_length=500, null=True, verbose_name='رمز الوصول الدائم (Access Token)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
        migrations.CreateModel(
            name='TrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الموبايل')),
                ('is_whatsapp', models.BooleanField(default=False, verbose_name='هل الرقم واتساب؟')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subscribe_whatsapp', models.BooleanField(default=False, verbose_name='الاشتراك بنشرة الواتساب')),
                ('subscribe_email', models.BooleanField(default=False, verbose_name='الاشتراك بنشرة الإيميل')),
                ('status', models.CharField(choices=[('new', 'طلب جديد'), ('contacted', 'تم التواصل'), ('activated', 'مُفعّل'), ('rejected', 'مرفوض')], default='new', max_length=10, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'طلب تجريبي',
                'verbose_name_plural': 'الطلبات التجريبية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_db_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='قاعدة بيانات الشركة التجريبية')),
                ('is_customer', models.BooleanField(default=True, verbose_name='زبون')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='مورد')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='صورة الملف الشخصي')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى'), ('O', 'آخر')], max_length=1, verbose_name='الجنس')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='نبذة شخصية')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='البلد')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('instagram', models.URLField(blank=True, verbose_name='انستغرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكدإن')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='الوظيفة')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='الشركة')),
                ('skills', models.CharField(blank=True, max_length=200, verbose_name='المهارات')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنوات الخبرة')),
                ('education_level', models.CharField(blank=True, choices=[('HS', 'ثانوي'), ('DIP', 'دبلوم'), ('BAC', 'بكالوريوس'), ('MAS', 'ماجستير'), ('PHD', 'دكتوراه'), ('OTH', 'أخرى')], max_length=3, verbose_name='مستوى التعليم')),
                ('university_major', models.CharField(blank=True, max_length=100, verbose_name='التخصص الجامعي')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='اللغات')),
                ('is_public', models.BooleanField(default=True, verbose_name='هل الملف الشخصي عام؟')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='تلقي إشعارات البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
