# Generated by Django 4.2.16 on 2026-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المقاس')),
                ('width', models.PositiveIntegerField(verbose_name='العرض (مم)')),
                ('height', models.PositiveIntegerField(verbose_name='الارتفاع (مم)')),
                ('is_default', models.BooleanField(default=False, verbose_name='المقاس الافتراضي')),
            ],
            options={
                'verbose_name': 'مقاس ملصق',
                'verbose_name_plural': 'مقاسات ملصقات الباركود',
                'ordering': ['width'],
            },
        ),
    ]
