# Generated by Django 6.0.5 on 2026-06-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_full_name_remove_profile_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('company_name', models.CharField(help_text='اسم نشاطك التجاري كما تريد أن يظهر', max_length=200, verbose_name='اسم النشاط / المتجر')),
                ('role', models.CharField(choices=[('owner', 'صاحب النشاط (أنا أسّس هذا الحلم)'), ('partner', 'شريك في النشاط'), ('manager', 'مدير مسؤول'), ('employee', 'موظف / مسؤول تقني')], max_length=50, verbose_name='دورك في النشاط')),
                ('business_type', models.CharField(choices=[('retail', 'تجارة تجزئة / سوبر ماركت / بقالة'), ('fashion', 'ملابس وأزياء / أجهزة وموبيلات'), ('food', 'مطاعم / كافيهات / تموينات'), ('wholesale', 'تجارة جملة / توزيع'), ('services', 'خدمات مهنية / حرفية / صيانة'), ('ecommerce', 'متجر إلكتروني فقط'), ('other', 'نشاط آخر')], max_length=50, verbose_name='طبيعة نشاطك')),
                ('country_code', models.CharField(default='+966', max_length=5, verbose_name='رمز الدولة')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('has_whatsapp', models.BooleanField(default=False, verbose_name='هل الرقم عليه واتساب؟')),
                ('subscribe_email', models.BooleanField(default=False, verbose_name='الاشتراك في النشرة البريدية')),
                ('subscribe_whatsapp', models.BooleanField(default=False, verbose_name='الاشتراك في نشرة الواتساب')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='تم التواصل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الموظف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
            ],
            options={
                'verbose_name': 'طلب فترة تجريبية',
                'verbose_name_plural': 'طلبات الفترة التجريبية',
                'ordering': ['-created_at'],
            },
        ),
    ]
