# Generated by Django 6.0.5 on 2026-06-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_trialrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialRequest',
        ),
    ]
