# Generated by Django 6.0.5 on 2026-06-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_trialrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الموبايل')),
                ('is_whatsapp', models.BooleanField(default=False, verbose_name='هل الرقم واتساب؟')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('subscribe_whatsapp', models.BooleanField(default=False, verbose_name='الاشتراك بنشرة الواتساب')),
                ('subscribe_email', models.BooleanField(default=False, verbose_name='الاشتراك بنشرة الإيميل')),
                ('status', models.CharField(choices=[('new', 'طلب جديد'), ('contacted', 'تم التواصل'), ('activated', 'مُفعّل'), ('rejected', 'مرفوض')], default='new', max_length=10, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طلب تجريبي',
                'verbose_name_plural': 'الطلبات التجريبية',
                'ordering': ['-created_at'],
            },
        ),
    ]
