# Generated by Django 6.0.5 on 2026-07-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_trialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialrequest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
