# Generated by Django 6.0.5 on 2026-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_trialrequest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_message1',
            field=models.CharField(blank=True, default='مرحباً، أتواصل معكم من المتجر، كيف يمكنكم مساعدتي؟', max_length=255, null=True, verbose_name='رسالة واتساب التلقائية'),
        ),
    ]
