# Generated by Django 6.0.5 on 2026-07-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_companysettings_whatsapp_message1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='whatsapp_message1',
        ),
    ]
