# Generated by Django 6.0.5 on 2026-07-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_companysettings_whatsapp_message1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university_major',
        ),
        migrations.AddField(
            model_name='profile',
            name='role_data',
            field=models.JSONField(blank=True, default=dict, help_text='تخزين البيانات الخاصة بكل دور بشكل منفصل', verbose_name='بيانات خاصة بالدور'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'زبون'), ('supplier', 'مورد'), ('vendor', 'بائع/متجر'), ('employee', 'موظف'), ('admin', 'مدير')], default='customer', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
