# Generated by Django 6.0.5 on 2026-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_profile_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role_data',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('HS', 'ثانوي'), ('DIP', 'دبلوم'), ('BAC', 'بكالوريوس'), ('MAS', 'ماجستير'), ('PHD', 'دكتوراه'), ('OTH', 'أخرى')], max_length=3, verbose_name='مستوى التعليم'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سنوات الخبرة'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='الوظيفة'),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='اللغات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='شعار الشركة'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=200, verbose_name='المهارات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university_major',
            field=models.CharField(blank=True, max_length=100, verbose_name='التخصص الجامعي'),
        ),
    ]
