# Generated by Django 6.0.5 on 2026-09-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_profile_role_data_remove_profile_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trial_db_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='قاعدة بيانات الشركة التجريبية'),
        ),
    ]
