# Generated by Django 4.2.16 on 2026-10-03 19:33

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Prodnots',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='ملاحظات'),
        ),
    ]
