# Generated by Django 4.2.16 on 2026-10-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_product_prodnots'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=100, verbose_name='اسم المواصفة')),
                ('spec_value', models.CharField(max_length=255, verbose_name='قيمة المواصفة')),
                ('spec_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المواصفة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='invoice.product', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'مواصفة',
                'verbose_name_plural': 'مواصفات إضافية',
                'ordering': ['spec_name'],
            },
        ),
    ]
