# Generated by Django 4.2.16 on 2026-10-04 17:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_prodspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم نوع المواصفة')),
            ],
            options={
                'verbose_name': 'نوع مواصفة',
                'verbose_name_plural': 'أنواع المواصفات',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='prodspec',
            options={'verbose_name': 'مواصفة', 'verbose_name_plural': 'مواصفات إضافية'},
        ),
        migrations.AddField(
            model_name='prodspec',
            name='show_on_barcode',
            field=models.BooleanField(default=False, verbose_name='إظهار في الباركود'),
        ),
        migrations.AddField(
            model_name='prodspec',
            name='spec_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر المواصفة'),
        ),
        migrations.CreateModel(
            name='SpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='القيمة')),
                ('spec_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='invoice.spectype', verbose_name='نوع المواصفة')),
            ],
            options={
                'verbose_name': 'قيمة مواصفة',
                'verbose_name_plural': 'قيم المواصفات',
                'ordering': ['value'],
            },
        ),
        migrations.AddField(
            model_name='prodspec',
            name='spec_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='invoice.spectype', verbose_name='نوع المواصفة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prodspec',
            name='spec_value',
            field=models.ForeignKey(limit_choices_to=models.Q(('spec_type', models.F('spec_type'))), on_delete=django.db.models.deletion.PROTECT, to='invoice.specvalue', verbose_name='قيمة المواصفة'),
        ),
        migrations.AlterUniqueTogether(
            name='prodspec',
            unique_together={('product', 'spec_type')},
        ),
        migrations.RemoveField(
            model_name='prodspec',
            name='spec_name',
        ),
    ]
