# Generated by Django 4.2.16 on 2026-10-07 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_spectype_alter_prodspec_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prodspec',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='prodspec',
            name='spec_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.spectype', verbose_name='نوع المواصفة'),
        ),
        migrations.AlterField(
            model_name='prodspec',
            name='spec_value',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('spec_type', models.F('spec_type'))), null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.specvalue', verbose_name='قيمة المواصفة'),
        ),
    ]
