# Generated by Django 6.0.4 on 2026-05-09 02:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_alter_product_main_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pricing_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.pricingtier', verbose_name='مستوى التسعير الافتراضي'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='email_host',
            field=models.CharField(max_length=255, verbose_name='SMTP Host'),
        ),
        migrations.AlterField(
            model_name='emailsetting',
            name='email_host_password',
            field=models.CharField(max_length=255, verbose_name='Email Password'),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='ends_at',
            field=models.DateTimeField(verbose_name='ينتهي في'),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='flashdeal',
            name='max_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='الكمية المخصصة للعرض'),
        ),
        migrations.AlterField(
            model_name='pricingtier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المستوى'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='invoice.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='الباركود الأساسي'),
        ),
        migrations.AlterField(
            model_name='productsectionitem',
            name='custom_badge',
            field=models.ImageField(blank=True, null=True, upload_to='store_section_badges/', verbose_name='شعار خاص (اختياري)'),
        ),
        migrations.AlterField(
            model_name='productstoresetting',
            name='store_section',
            field=models.CharField(choices=[('none', 'بدون قسم'), ('offers', 'أحدث العروض'), ('new', 'منتجات جديدة'), ('products', 'منتجاتنا')], default='products', max_length=20, verbose_name='القسم في المتجر'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='purchased_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الكمية الأساسية'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='return_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='storeannouncement',
            name='icon_class',
            field=models.CharField(default='fa-bullhorn', max_length=50, verbose_name='رمز الأيقونة'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='storebanner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='العنوان الترويجي'),
        ),
        migrations.AlterField(
            model_name='storesection',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب القسم'),
        ),
        migrations.AlterField(
            model_name='storesection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم القسم'),
        ),
    ]
