# Generated by Django 6.0.4 on 2026-05-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_alter_category_pricing_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsetting',
            name='pricing_password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='كلمة مرور نظام التسعير (مشفرة)'),
        ),
    ]
