# Generated by Django 6.0.5 on 2026-05-15 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_pricingsetting_pricing_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_sections', to='invoice.category', verbose_name='التصنيف المرتبط'),
        ),
    ]
