# Generated by Django 6.0.5 on 2026-05-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_storesection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesection',
            name='is_offers_style',
            field=models.BooleanField(default=False, verbose_name='شكل عروض مميز'),
        ),
    ]
