# Generated by Django 6.0.5 on 2026-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_storesection_is_offers_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_operation_type',
            field=models.CharField(blank=True, choices=[('purchase', 'مشتريات'), ('sale', 'مبيعات'), ('sale_return', 'مرتجع مبيعات'), ('purchase_return', 'مرتجع مشتريات')], max_length=20, null=True, verbose_name='نوع آخر عملية'),
        ),
    ]
