# Generated by Django 6.0.5 on 2026-06-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_alter_product_last_operation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingsetting',
            name='offer_1_percent',
        ),
        migrations.RemoveField(
            model_name='pricingsetting',
            name='offer_2_percent',
        ),
        migrations.RemoveField(
            model_name='pricingsetting',
            name='offer_3_percent',
        ),
        migrations.RemoveField(
            model_name='pricingsetting',
            name='offer_4_percent',
        ),
        migrations.RemoveField(
            model_name='pricingsetting',
            name='offer_5_percent',
        ),
        migrations.RemoveField(
            model_name='pricingsetting',
            name='offer_6_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_1_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_2_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_3_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_4_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_5_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_6_price',
        ),
    ]
